### ISSUE TITLE
Builds failing tsc on AzureDevOps hosted agent

### ISSUE THREAD

**Issue by jeffpriz** [microsoft/azure-devops-node-api#326]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 
Npm version: 6.9.0
OS and version: v10.15.3 win32 x64
azure-devops-node-api version: 8.0.0

### Issue Description
I build my Azure DevOps extension that uses this api on a Hosted Azure Devops build agent.  The builds have begun failing the TSC step with the following errors.  I've built a commit from 3 days ago that I built successfully then, but fails to build today..  Help?
npm ERR! 
node_modules/azure-devops-node-api/BuildApi.d.ts(89,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR! Failed at the vsts-release-web-test@1.0.0 build script.
node_modules/azure-devops-node-api/CoreApi.d.ts(41,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node_modules/azure-devops-node-api/DashboardApi.d.ts(22,40): error TS1039: Initializers are not allowed in ambient contexts.

node_modules/azure-devops-node-api/ExtensionManagementApi.d.ts(34,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR! A complete log of this run can be found in:
node_modules/azure-devops-node-api/GalleryApi.d.ts(93,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR!     C:\npm\cache\_logs\2019-06-11T12_08_33_113Z-debug.log
node_modules/azure-devops-node-api/GitApi.d.ts(133,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/PolicyApi.d.ts(20,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/ProjectAnalysisApi.d.ts(12,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/ReleaseApi.d.ts(94,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(166,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/TestApi.d.ts(88,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/TfvcApi.d.ts(33,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WikiApi.d.ts(20,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkApi.d.ts(64,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(100,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkItemTrackingProcessApi.d.ts(62,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkItemTrackingProcessDefinitionsApi.d.ts(53,40): error TS1039: Initializers are not allowed in ambient contexts.

### Steps to reproduce
1. 
2. 
3. 
4. 
5. 

### Logs
##[section]Starting: npm custom
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Package Management.
Version      : 1.151.1
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\npm.cmd --version"
6.9.0
[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\npm.cmd config list"
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.15.3 win32 x64"

; environment configs
cache = "C:\\npm\\cache"
prefix = "C:\\npm\\prefix"
userconfig = "D:\\a\\1\\npm\\2893.npmrc"

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\a\1\s\backlogCopy
; HOME = C:\Users\VssAdministrator
; "npm config ls -l" to show all defaults.

[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\npm.cmd run build"
npm ERR! code ELIFECYCLE

npm ERR! errno 2
> vsts-release-web-test@1.0.0 build D:\a\1\s\backlogCopy
npm ERR! vsts-release-web-test@1.0.0 build: `tsc.cmd`
> tsc.cmd
npm ERR! Exit status 2

npm ERR! 
node_modules/azure-devops-node-api/BuildApi.d.ts(89,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR! Failed at the vsts-release-web-test@1.0.0 build script.
node_modules/azure-devops-node-api/CoreApi.d.ts(41,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node_modules/azure-devops-node-api/DashboardApi.d.ts(22,40): error TS1039: Initializers are not allowed in ambient contexts.

node_modules/azure-devops-node-api/ExtensionManagementApi.d.ts(34,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR! A complete log of this run can be found in:
node_modules/azure-devops-node-api/GalleryApi.d.ts(93,40): error TS1039: Initializers are not allowed in ambient contexts.
npm ERR!     C:\npm\cache\_logs\2019-06-11T12_08_33_113Z-debug.log
node_modules/azure-devops-node-api/GitApi.d.ts(133,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/PolicyApi.d.ts(20,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/ProjectAnalysisApi.d.ts(12,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/ReleaseApi.d.ts(94,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(166,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/TestApi.d.ts(88,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/TfvcApi.d.ts(33,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WikiApi.d.ts(20,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkApi.d.ts(64,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(100,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkItemTrackingProcessApi.d.ts(62,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/azure-devops-node-api/WorkItemTrackingProcessDefinitionsApi.d.ts(53,40): error TS1039: Initializers are not allowed in ambient contexts.
Found npm debug log, make sure the path matches with the one in npm's output: C:\npm\cache\_logs\2019-06-11T12_08_33_113Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\npm\\prefix\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vsts-release-web-test@1.0.0~prebuild: vsts-release-web-test@1.0.0
6 info lifecycle vsts-release-web-test@1.0.0~build: vsts-release-web-test@1.0.0
7 verbose lifecycle vsts-release-web-test@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vsts-release-web-test@1.0.0~build: PATH: C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\a\1\s\backlogCopy\node_modules\.bin;C:\hostedtoolcache\windows\tfx\0.6.4\x64;C:\agents\2.150.3\externals\git\cmd;C:/hostedtoolcache/windows\Python\3.6.8\x64;C:/hostedtoolcache/windows\Python\3.6.8\x64\Scripts;C:\Program Files\Mercurial\;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\Program Files\Boost\1.69.0;C:\Users\VssAdministrator\.dotnet\tools;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\zulu-8-azure-jdk_8.38.0.13-8.0.212-win_x64\bin;C:\npm\prefix;C:\Program Files\Rust\.cargo\bin;C:\hostedtoolcache\windows\Ruby\2.5.3\x64\bin;C:\Go1.12.4\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\hostedtoolcache\windows\Python\3.6.8\Scripts;C:\hostedtoolcache\windows\Python\3.6.8;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft MPI\Bin\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\6\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;c:\tools\php;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\OpenSSL\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle vsts-release-web-test@1.0.0~build: CWD: D:\a\1\s\backlogCopy
10 silly lifecycle vsts-release-web-test@1.0.0~build: Args: [ '/d /s /c', 'tsc.cmd' ]
11 silly lifecycle vsts-release-web-test@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle vsts-release-web-test@1.0.0~build: Failed to exec build script
13 verbose stack Error: vsts-release-web-test@1.0.0 build: `tsc.cmd`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\npm\prefix\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vsts-release-web-test@1.0.0
15 verbose cwd D:\a\1\s\backlogCopy
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\npm\\prefix\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error vsts-release-web-test@1.0.0 build: `tsc.cmd`
22 error Exit status 2
23 error Failed at the vsts-release-web-test@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

##[error]Error: Npm failed with return code: 2
##[section]Finishing: npm custom

**Comment by stephenmichaelf** [comment]
@jeffpriz When you say exact commit I assume that means of your project? Are you referencing this lib using a specific version or a ~/^? Can you check the version of tsc you're using?

When I've seen this issue in the past it's been due to Typescript compiler version.

**Comment by jeffpriz** [comment]
@stephenmichaelf  So my Package.json did look like this:
  "devDependencies": {
    "typescript": "^2.4.2",
    "@types/node": "^6.0.31"
  },
  "files": [
    "dist/",
    "src/",
    "config/"
  ],
  "dependencies": {
    "azure-pipelines-task-lib": "^2.8.0",
    "azure-devops-node-api": "^8.0.0",
    "reflect-metadata": "^0.1.10",
    "tslib": "^1.9.3",
    "xml-parser": "^1.2.1",
    "xmldom": "^0.1.27"
  }

Interestingly if I update the azure-devop-node-api reference locally to 8.1.1 instead of 8.0.0 i fail the tsc.cmd locally with those same errors.    So I'm not sure what happened between 8.0 and 8.1.1.. 

If I update my dependencies for typescript:
  "devDependencies": {
    "typescript": "3.1.5",
    "@types/node": "8.9.2"
  },


then  I build with the azure-devops-node-api set to 8.1.1 I still get errors below.. I guess What are the correct typescript version to build with 8.1.1?  I tried upping the api to 9.0.0 as I see that was published a couple days back, which builds fine, but I get a weird runtime error about locating the package.json ? 

node_modules/azure-devops-node-api/BuildApi.d.ts:89:40 - error TS1039: Initializers are not allowed in ambient contexts.

89     static readonly RESOURCE_AREA_ID = "965220d5-5bb9-42cf-8d67-9b146df2a5a4";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/CoreApi.d.ts:41:40 - error TS1039: Initializers are not allowed in ambient contexts.

41     static readonly RESOURCE_AREA_ID = "79134c72-4a58-4b42-976c-04e7115f32bf";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/DashboardApi.d.ts:22:40 - error TS1039: Initializers are not allowed in ambient contexts.

22     static readonly RESOURCE_AREA_ID = "31c84e0a-3ece-48fd-a29d-100849af99ba";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/ExtensionManagementApi.d.ts:34:40 - error TS1039: Initializers are not allowed in ambient contexts.

34     static readonly RESOURCE_AREA_ID = "6c2b0933-3600-42ae-bf8b-93d4f7e83594";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/GalleryApi.d.ts:93:40 - error TS1039: Initializers are not allowed in ambient contexts.

93     static readonly RESOURCE_AREA_ID = "69d21c00-f135-441b-b5ce-3626378e0819";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/GitApi.d.ts:133:40 - error TS1039: Initializers are not allowed in ambient contexts.

133     static readonly RESOURCE_AREA_ID = "4e080c62-fa21-4fbc-8fef-2a10a2b38049";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/PolicyApi.d.ts:20:40 - error TS1039: Initializers are not allowed in ambient contexts.

20     static readonly RESOURCE_AREA_ID = "fb13a388-40dd-4a04-b530-013a739c72ef";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/ProjectAnalysisApi.d.ts:12:40 - error TS1039: Initializers are not allowed in ambient contexts.

12     static readonly RESOURCE_AREA_ID = "7658fa33-b1bf-4580-990f-fac5896773d3";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/ReleaseApi.d.ts:94:40 - error TS1039: Initializers are not allowed in ambient contexts.

94     static readonly RESOURCE_AREA_ID = "efc2f575-36ef-48e9-b672-0c6fb4a48ac5";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts:166:40 - error TS1039: Initializers are not allowed in ambient contexts.

166     static readonly RESOURCE_AREA_ID = "a85b8835-c1a1-4aac-ae97-1c3d0ba72dbd";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/TestApi.d.ts:88:40 - error TS1039: Initializers are not allowed in ambient contexts.

88     static readonly RESOURCE_AREA_ID = "c2aa639c-3ccc-4740-b3b6-ce2a1e1d984e";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/TfvcApi.d.ts:33:40 - error TS1039: Initializers are not allowed in ambient contexts.

33     static readonly RESOURCE_AREA_ID = "8aa40520-446d-40e6-89f6-9c9f9ce44c48";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/WikiApi.d.ts:20:40 - error TS1039: Initializers are not allowed in ambient contexts.

20     static readonly RESOURCE_AREA_ID = "bf7d82a0-8aa5-4613-94ef-6172a5ea01f3";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/WorkApi.d.ts:64:40 - error TS1039: Initializers are not allowed in ambient contexts.

64     static readonly RESOURCE_AREA_ID = "1d4f49f9-02b9-4e26-b826-2cdb6195f2a9";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts:100:40 - error TS1039: Initializers are not allowed in ambient contexts.

100     static readonly RESOURCE_AREA_ID = "5264459e-e5e0-4bd8-b118-0985e68a4ec5";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/WorkItemTrackingProcessApi.d.ts:62:40 - error TS1039: Initializers are not allowed in ambient contexts.

62     static readonly RESOURCE_AREA_ID = "5264459e-e5e0-4bd8-b118-0985e68a4ec5";
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/azure-devops-node-api/WorkItemTrackingProcessDefinitionsApi.d.ts:53:40 - error TS1039: Initializers are not allowed in ambient contexts.

53     static readonly RESOURCE_AREA_ID = "5264459e-e5e0-4bd8-b118-0985e68a4ec5";

**Comment by stephenmichaelf** [comment]
There was a bug with 9.0.0, there is a fix in and we should be deploying it today.

As far as the build issue, I am unable to recreate it. I used the following dependencies in package.json:

`"dependencies": {
    ...
    "azure-devops-node-api": "8.0.0"
  },
  "devDependencies": {
    ...
    "typescript": "^2.4.2"
  }`

This built fine.

Can you share your full package.json?

**Comment by jeffpriz** [comment]
right, so building with 8.0.0 will not cause a build issue.. building with 8.1.1 WILL cause a build issue.  
 


[package.json.txt](https://github.com/microsoft/azure-devops-node-api/files/3276952/package.json.txt)

**Comment by stephenmichaelf** [comment]
9.0.1 has been released. Can you try that?

**Comment by jeffpriz** [comment]
Version 9.0.1 build successfully, and I no longer receive the runtime error about the package.json.. so that's good..

**Comment by jeffpriz** [comment]
created issue https://github.com/microsoft/azure-devops-node-api/issues/327 for the trouble with createing an Area.. I think you've solved the original issue for this issue! thanks

**Comment by stephenmichaelf** [comment]
Of course! Closing as it's resolved.
